/**
 * Mock — Dr Brilho Estética Automotiva (UI only).
 * Fotos Unsplash em /public/mock — apagar quando houver upload/API reais.
 */

const img = (file) => `/mock/${file}`

export const mockEstabelecimento = {
  nome: 'Dr Brilho Estética Automotiva',
  cidade: 'Região metropolitana',
  tom: 'Estética automotiva e produtos de detalhamento',
}

/** Páginas/links compartilháveis (aba Catálogos). */
export const mockCatalogos = [
  {
    id: 'cat-1',
    nome: 'Produtos Dr Brilho',
    descricao: 'Linha completa para o cliente levar: limpeza, brilho e proteção.',
    categoria: 'Produtos',
    badge: 'Ativo',
    itens: 12,
    imagem: img('cat-produtos.jpg'),
  },
  {
    id: 'cat-2',
    nome: 'Promoções da semana',
    descricao: 'Ofertas rotativas de produtos — ideal para o status do WhatsApp.',
    categoria: 'Produtos',
    badge: 'Novo',
    itens: 5,
    imagem: img('cat-promo.jpg'),
  },
  {
    id: 'cat-3',
    nome: 'Cardápio de serviços',
    descricao: 'Todos os serviços da estética com preço a partir de — um link só.',
    categoria: 'Serviços',
    badge: 'Ativo',
    itens: 14,
    imagem: img('cat-servicos.jpg'),
  },
  {
    id: 'cat-4',
    nome: 'Campanha: Cristalização',
    descricao: 'Foco num serviço — dá para usar depois em anúncio ou story.',
    categoria: 'Campanha',
    badge: 'Destaque',
    itens: 1,
    imagem: img('cat-cristalizacao.jpg'),
  },
]

/** Peças gráficas rápidas (aba Panfletos). */
export const mockPanfletos = [
  {
    id: 'pan-1',
    nome: 'Lavagem completa — fim de semana',
    descricao: 'Arte pronta para imprimir ou mandar no zap do cliente.',
    categoria: 'Promoção',
    badge: 'Ativo',
    imagem: img('panfleto-lavagem.jpg'),
  },
  {
    id: 'pan-2',
    nome: 'Combo interior + exterior',
    descricao: 'Panfleto do pacote mais pedido da casa.',
    categoria: 'Pacote',
    badge: 'Destaque',
    imagem: img('panfleto-combo.jpg'),
  },
  {
    id: 'pan-3',
    nome: 'Black de brilho — 20% off',
    descricao: 'Campanha sazonal de produtos e serviços.',
    categoria: 'Campanha',
    badge: 'Novo',
    imagem: img('panfleto-promo.jpg'),
  },
  {
    id: 'pan-4',
    nome: 'Abertura da loja',
    descricao: 'Convite / apresentação Dr Brilho para a vizinhança.',
    categoria: 'Institucional',
    imagem: img('panfleto-flyer.jpg'),
  },
]

/** Cartões digitais/imprimíveis (aba Cartões). */
export const mockCartoes = [
  {
    id: 'card-1',
    nome: 'Carlos Mendes — Proprietário',
    descricao: 'Cartão do dono: WhatsApp, Instagram e endereço da estética.',
    categoria: 'Direção',
    badge: 'Ativo',
    imagem: img('cartao-dono.jpg'),
  },
  {
    id: 'card-2',
    nome: 'Juliana Reis — Consultora de vendas',
    descricao: 'Cartão da representante: foco em produtos e combos para revenda.',
    categoria: 'Vendas',
    badge: 'Ativo',
    imagem: img('cartao-vendas.jpg'),
  },
]

export const mockProdutos = [
  {
    id: 'prod-1',
    nome: 'Limpador de vidros 500ml',
    descricao: 'Sem manchas — uso interno e externo.',
    categoria: 'Vidros',
    badge: 'Popular',
    imagem: img('prod-limpador-vidro.jpg'),
    preco: 'R$ 28,90',
  },
  {
    id: 'prod-2',
    nome: 'Shampoo automotivo 1L',
    descricao: 'pH neutro, alta espuma — lavagem a mão.',
    categoria: 'Lavagem',
    badge: 'Destaque',
    imagem: img('prod-shampoo-auto.jpg'),
    preco: 'R$ 42,00',
  },
  {
    id: 'prod-3',
    nome: 'Toalha de microfibra (un.)',
    descricao: '400 GSM — secagem sem riscos.',
    categoria: 'Acessórios',
    imagem: img('prod-microfibra.jpg'),
    preco: 'R$ 19,90',
  },
  {
    id: 'prod-4',
    nome: 'Cera líquida de carnaúba 300ml',
    descricao: 'Brilho e proteção por até 30 dias.',
    categoria: 'Proteção',
    badge: 'Novo',
    imagem: img('prod-cera.jpg'),
    preco: 'R$ 67,00',
  },
  {
    id: 'prod-5',
    nome: 'Pretinho para pneus 500ml',
    descricao: 'Acabamento acetinado, sem respingo na pintura.',
    categoria: 'Pneus',
    imagem: img('prod-pneu.jpg'),
    preco: 'R$ 35,50',
  },
  {
    id: 'prod-6',
    nome: 'Limpa couro / vinil 400ml',
    descricao: 'Painel, portas e bancos sintéticos.',
    categoria: 'Interior',
    imagem: img('prod-interior.jpg'),
    preco: 'R$ 39,90',
  },
  {
    id: 'prod-7',
    nome: 'Desengraxante APC 1L',
    descricao: 'Multiuso concentrado — motor e chassis.',
    categoria: 'Limpeza',
    imagem: img('prod-desengraxante.jpg'),
    preco: 'R$ 48,00',
  },
  {
    id: 'prod-8',
    nome: 'Revitalizador de plásticos 200ml',
    descricao: 'Para para-choque e acabamentos externos.',
    categoria: 'Proteção',
    badge: 'Promoção',
    imagem: img('prod-revitalizador.jpg'),
    preco: 'R$ 44,90',
    precoDe: 'R$ 52,00',
  },
  {
    id: 'prod-9',
    nome: 'Aplicador de espuma (un.)',
    descricao: 'Espuma macia para cera e dressagem.',
    categoria: 'Acessórios',
    imagem: img('prod-aplicador.jpg'),
    preco: 'R$ 12,00',
  },
  {
    id: 'prod-10',
    nome: 'Kit limpeza rápida (3 itens)',
    descricao: 'Shampoo amostra + microfibra + limpador de vidro.',
    categoria: 'Kits',
    badge: 'Combo prateleira',
    imagem: img('prod-kit-limpeza.jpg'),
    preco: 'R$ 59,90',
  },
]

export const mockCombos = [
  {
    id: 'combo-1',
    nome: 'Kit lavagem completa',
    descricao: 'Shampoo 1L + 2 microfibras + pretinho 500ml.',
    categoria: 'Lavagem',
    badge: 'Destaque',
    imagem: img('combo-lavagem.jpg'),
    preco: 'R$ 89,90',
    precoDe: 'R$ 109,00',
  },
  {
    id: 'combo-2',
    nome: 'Kit interior premium',
    descricao: 'Limpa couro + APC 1L + aplicador + microfibra.',
    categoria: 'Interior',
    badge: 'Popular',
    imagem: img('combo-interior.jpg'),
    preco: 'R$ 99,00',
    precoDe: 'R$ 118,00',
  },
  {
    id: 'combo-3',
    nome: 'Kit brilho e proteção',
    descricao: 'Cera carnaúba + revitalizador de plásticos + aplicador.',
    categoria: 'Proteção',
    badge: 'Novo',
    imagem: img('combo-brilho.jpg'),
    preco: 'R$ 119,00',
    precoDe: 'R$ 135,00',
  },
  {
    id: 'combo-4',
    nome: 'Kit vidros e pneus',
    descricao: 'Limpador de vidros + pretinho — combo rápido de acabamento.',
    categoria: 'Acabamento',
    imagem: img('prod-limpador-vidro.jpg'),
    preco: 'R$ 54,90',
  },
]

export const mockServicos = [
  {
    id: 'srv-1',
    nome: 'Lavagem simples',
    descricao: 'Externo com shampoo neutro e secagem em microfibra.',
    categoria: 'Lavagem',
    badge: 'Popular',
    imagem: img('srv-lavagem.jpg'),
    preco: 'A partir de R$ 40',
  },
  {
    id: 'srv-2',
    nome: 'Lavagem completa',
    descricao: 'Externo + aspiração + painéis + vidros.',
    categoria: 'Lavagem',
    badge: 'Destaque',
    imagem: img('srv-lavagem-tecnica.jpg'),
    preco: 'A partir de R$ 80',
  },
  {
    id: 'srv-3',
    nome: 'Lavagem técnica',
    descricao: 'Descontaminação leve, duas baldes e acabamento de pneus.',
    categoria: 'Lavagem',
    imagem: img('srv-lavagem.jpg'),
    preco: 'A partir de R$ 120',
  },
  {
    id: 'srv-4',
    nome: 'Higienização interna',
    descricao: 'Bancos, carpete, teto e eliminação de odores leves.',
    categoria: 'Interior',
    badge: 'Popular',
    imagem: img('srv-higienizacao.jpg'),
    preco: 'A partir de R$ 180',
  },
  {
    id: 'srv-5',
    nome: 'Higienização a vapor',
    descricao: 'Vapor em bancos e carpetes — menos química agressiva.',
    categoria: 'Interior',
    imagem: img('srv-vapor.jpg'),
    preco: 'A partir de R$ 220',
  },
  {
    id: 'srv-6',
    nome: 'Polimento técnico',
    descricao: 'Correção de hologramas e recuperação de brilho.',
    categoria: 'Pintura',
    badge: 'Destaque',
    imagem: img('srv-polimento.jpg'),
    preco: 'A partir de R$ 450',
  },
  {
    id: 'srv-7',
    nome: 'Cristalização / vitrificação',
    descricao: 'Proteção duradoura com efeito espelhado.',
    categoria: 'Proteção',
    badge: 'Campanha',
    imagem: img('srv-cristalizacao.jpg'),
    preco: 'A partir de R$ 890',
  },
  {
    id: 'srv-8',
    nome: 'Restauração de faróis',
    descricao: 'Lixamento, polimento e selagem UV.',
    categoria: 'Faróis',
    badge: 'Novo',
    imagem: img('srv-farol.jpg'),
    preco: 'A partir de R$ 150',
  },
  {
    id: 'srv-9',
    nome: 'Hidratação de bancos (couro)',
    descricao: 'Limpeza + hidratante para couro natural.',
    categoria: 'Couro',
    imagem: img('srv-hidratacao-couro.jpg'),
    preco: 'A partir de R$ 160',
  },
  {
    id: 'srv-10',
    nome: 'Limpeza e hidratação de bancos (tecido)',
    descricao: 'Extração de sujeira e revitalização das fibras.',
    categoria: 'Interior',
    imagem: img('srv-bancos.jpg'),
    preco: 'A partir de R$ 140',
  },
  {
    id: 'srv-11',
    nome: 'Limpeza de motor',
    descricao: 'Desengraxante controlado e proteção de bornes.',
    categoria: 'Motor',
    imagem: img('srv-motor.jpg'),
    preco: 'A partir de R$ 90',
  },
  {
    id: 'srv-12',
    nome: 'Tratamento de vidros (antiembaçante)',
    descricao: 'Aplicação em para-brisas e laterais.',
    categoria: 'Vidros',
    imagem: img('srv-vidros.jpg'),
    preco: 'A partir de R$ 70',
  },
  {
    id: 'srv-13',
    nome: 'Pretinho e acabamento de pneus',
    descricao: 'Dressagem com secagem controlada.',
    categoria: 'Pneus',
    imagem: img('srv-pretinho.jpg'),
    preco: 'A partir de R$ 35',
  },
  {
    id: 'srv-14',
    nome: 'Remoção de odores',
    descricao: 'Ozônio / tratamento para cheiro de cigarro ou umidade.',
    categoria: 'Interior',
    imagem: img('srv-odor.jpg'),
    preco: 'Sob orçamento',
  },
]
